all: testytest

testytest:
	$ g++ -std=c++11 -o testytest gardensTest.cpp gardensStudent.cpp 

gradygrade:
	$ g++ -std=c++11 -o gradygrade gardensGrading.cpp gardensStudent.cpp 

clean: 
	rm -rf *.o testytest gradygrade
